// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package testing

// Injectors from injector.go:

func InitializeRoute() *SimpleRoute {
	simpleRepository := NewSimpleRepository()
	simpleService := NewSimpleService(simpleRepository)
	simpleController := NewSimpleController(simpleService)
	simpleRoute := NewSimpleRoute(simpleController)
	return simpleRoute
}
