// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user_routes

import (
	"database/sql"
	"github.com/go-playground/validator"
	"go_share/controller/user_controller"
	"go_share/repository/user_repository"
	"go_share/service/user_service"
)

// Injectors from user_injector.go:

func InitializeUserRoute(db *sql.DB, validate *validator.Validate) *UserRoutesImpl {
	userRepository := user_repository.NewUserRepository()
	userService := user_service.NewUserService(userRepository, db, validate)
	userController := user_controller.NewUserController(userService)
	userRoutesImpl := NewUserRoutes(userController)
	return userRoutesImpl
}
